### ISSUE TITLE
Add Card Selection Screen

### ISSUE THREAD

**Issue by lunaticcoding** [lunaticcoding/MilleSandersApp#1]
# TODO's
- [x] Add TabBar
- [x] Import Icons
- [x] Display Card Selection

**Comment by lunaticcoding** [comment]
<img width="334" alt="Screenshot 2020-04-09 at 20 48 50" src="https://user-images.githubusercontent.com/26603883/78929939-8651ff00-7aa3-11ea-8102-3c6629514605.png">

**Comment by lunaticcoding** [comment]
@val1mor Schau s mal durch :P Sollte aber so sein wie ma s uns beim design ausgemacht haben :D (es mille sanders logo brauch i no als svg :P vlt ah ohne den kreis außen rum so wie i da auf WhatsApp geschickt hab)

**Comment by val1mor** [comment]
Des erste Icon unten links sollte dann durch des Mille Sanders logo getauscht werde (logo als svg im google drive folder) 

für die Startseite wärn oben rechts Links zu den Social Media Kanälen cool
icons dafür stell ich heute nachmittag in den google drive folder)

Hier die Deckseiten Grund - Ansichten: 

![MilleSanders_Decks_app-02](https://user-images.githubusercontent.com/14888743/78993080-31fb5d80-7b3d-11ea-871c-739bbd3a9788.png)
![MilleSanders_Decks_app-04](https://user-images.githubusercontent.com/14888743/78993081-332c8a80-7b3d-11ea-88e9-030b4d8a0ed3.png)
![MilleSanders_Decks_app_Zeichenfläche 1](https://user-images.githubusercontent.com/14888743/78993082-33c52100-7b3d-11ea-88b0-a723390e4b9d.png)

**Comment by lunaticcoding** [comment]
@val1mor Logo mach i no rein :) 

bitte screen 1 und 2 (die beiden wo aktiv die Zitate angezeigt werden in #2 verschieben) und no ganz wichtig :) gib ma doch bitte a liste von beispielzitate (nit mehr als 10 und mehr als 3 wären cool :)) 

Dann wollen ma dass es durchrotiert wenn ma alle hat oder lieber so a " no more cards available card was dann die letzte isch? Werbungscards würd i daweil raus lassen, de können ma später no dazu tun :) 

Und da sein ma jetzt so, dass es mittlere icon aktiv isch für den tab, richtig? :)

**Comment by lunaticcoding** [comment]
@val1mor I bräuchte no die social media icons mit jeweiligen links :) bitte danke 

<img width="351" alt="Screenshot 2020-04-10 at 16 52 07" src="https://user-images.githubusercontent.com/26603883/78999847-c2409f00-7b4b-11ea-96a2-abea425310e2.png">

**Comment by val1mor** [comment]
> 
> 
> @val1mor Logo mach i no rein :)
> 
> bitte screen 1 und 2 (die beiden wo aktiv die Zitate angezeigt werden in #2 verschieben) und no ganz wichtig :) gib ma doch bitte a liste von beispielzitate (nit mehr als 10 und mehr als 3 wären cool :))
> 
> Dann wollen ma dass es durchrotiert wenn ma alle hat oder lieber so a " no more cards available card was dann die letzte isch? Werbungscards würd i daweil raus lassen, de können ma später no dazu tun :)
> 
> Und da sein ma jetzt so, dass es mittlere icon aktiv isch für den tab, richtig? :)
@lunaticcoding
___
1. hab die beiden Screens in #2 importiert. 

2. ok dann gib i da am besten glei drei verschiedene Formate:
https://docs.google.com/document/d/1EEKycbCHY01uczgWS7SSfk5cCsGc_beSvPpeHNSENW8/edit?usp=sharing

3. Ja Werbekarten brauchen ma no nit 👍 

4. Wenn alle KArten durchgescrollt sein wärn cool wenn so a button kimmt: neu mischen

5. Mitm mittleren Icon kommt ma zurück zur Startseite, also aktiv können eig alle sein, weil koans wirklich mit da Deck Seite direkt zu tun hat.

**Comment by val1mor** [comment]
@lunaticcoding 

Die Social Media Icons hab i in Google drive gladn
Hier no die Links:
Linkedin: https://www.linkedin.com/company/millesanders-com
Instagram: https://www.instagram.com/mille_sanders/
Pinterest: https://www.pinterest.at/millesanders/
Facebook: https://www.facebook.com/millesandersaustria/

**Comment by lunaticcoding** [comment]
@val1mor perfekt :D danke

**Comment by val1mor** [comment]
@lunaticcoding  die geänderten SVGs sind jetzt im google drive verzeichnis und i hab no des filter icon dazuglegt
