### ISSUE TITLE
Add Screen to display all the cards in one deck 

### ISSUE THREAD

**Issue by lunaticcoding** [lunaticcoding/MilleSandersApp#2]
# TODO's
- [x] Make Cards iterable in View
- [x] Implement Filter functionality

**Comment by val1mor** [comment]
![MilleSanders_Decks_app-02](https://user-images.githubusercontent.com/14888743/79010321-050d7180-7b62-11ea-9446-703ec4514b04.png)
![MilleSanders_Decks_app-04](https://user-images.githubusercontent.com/14888743/79010323-063e9e80-7b62-11ea-937c-503933f3996d.png)

**Comment by lunaticcoding** [comment]
@val1mor die pfeil icons fehlen no und schau bitte ob wirklich an dropshadow beim filter Auswahl popup willsch (hab da einfach den Hintergrund bissi ausgegraut)
